INSERT [dbo].[DM_NV] ([F1], [F2], [HoTen], [CK], [NamSinh], [F6], [TinhThanh], [LoaiHD], [GioiTinh], [F14], [DiaChi], [F16], [Phone]) VALUES (1, N'01', N'NGUYỄN HỮU BÌNH ', N'Bác sĩ chuyên khoa ngoại', CAST(N'1960-02-04T00:00:00.000' AS DateTime), N'215281328', N'Bình Định ', N'Không xác định thời hạn', N'Nam ', N'Quảng Nam ', N'Tổ 18 Phường Hòa Thọ Đông, Quận Cẩm Lệ, TP Đà Nẵng ', N'Lô 10 Đường Thăng Long, P.Hòa Thọ Đông, Q.Cẩm Lệ, TP Đà Nẵng ', N'090 511 2828')
GO
INSERT [dbo].[DM_NV] ([F1], [F2], [HoTen], [CK], [NamSinh], [F6], [TinhThanh], [LoaiHD], [GioiTinh], [F14], [DiaChi], [F16], [Phone]) VALUES (2, N'02', N'VÒNG THỊ THUÝ MAI', N'Cử nhân tài chính kế toán', CAST(N'1976-10-01T00:00:00.000' AS DateTime), N'271290328', N'Đồng Nai', N'Không xác định thời hạn', N'Nữ', N'Lạng Sơn', N'2/2, khu phố 8, phường Tân Phong, TP Biên Hòa, tỉnh Đồng Nai', N'2/2, khu phố 8, phường Tân Phong, TP Biên Hòa, tỉnh Đồng Nai', N'098 976 3532')
GO
INSERT [dbo].[DM_NV] ([F1], [F2], [HoTen], [CK], [NamSinh], [F6], [TinhThanh], [LoaiHD], [GioiTinh], [F14], [DiaChi], [F16], [Phone]) VALUES (3, N'03', N'VÒNG THỊ THÚY PHƯỢNG', N'Cử nhân kinh tế', CAST(N'1960-12-02T00:00:00.000' AS DateTime), N'272039717', N'Đồng Nai', N'Không xác định thời hạn', N'Nữ', N'Lạng Sơn', N'188/3, KP.3, P.Bình Đa, TP. Biên Hòa, tỉnh Đồng Nai', N'188/3, KP.3, P.Bình Đa, TP. Biên Hòa, tỉnh Đồng Nai', N'091 815 8237')
GO
INSERT [dbo].[DM_NV] ([F1], [F2], [HoTen], [CK], [NamSinh], [F6], [TinhThanh], [LoaiHD], [GioiTinh], [F14], [DiaChi], [F16], [Phone]) VALUES (4, N'04', N'NGUYỄN NHẬT MINH', N'Bác sĩ chuyên khoa YHCT', NULL, N'201591994', N'Đà Nẵng', N'Không xác định thời hạn', N'Nam ', N'Đà Nẵng ', N'Tổ 20 Phường Hòa Thọ Tây, Cẩm Lệ, TP Đà Nẵng', N'Tổ 20 Phường Hòa Thọ Tây, Cẩm Lệ, Đà Nẵng', N'090 567 3326')
GO
INSERT [dbo].[DM_NV] ([F1], [F2], [HoTen], [CK], [NamSinh], [F6], [TinhThanh], [LoaiHD], [GioiTinh], [F14], [DiaChi], [F16], [Phone]) VALUES (5, N'05', N'TRƯƠNG DIÊN LONG ', N'Bác sĩ chuyên khoa nội', NULL, N'201319611', N'Đà Nẵng', N'Không xác định thời hạn', N'Nam ', N'Đà Nẵng ', N'244 Nguyễn Công Trứ, Phường An Hải Đông, Quận Sơn Trà, TP Đà Nẵng ', N'244 Nguyễn Công Trứ, Phường An Hải Đông, Quận  Sơn Trà, TP Đà Nẵng ', N'093 331 6707')
GO
INSERT [dbo].[DM_NV] ([F1], [F2], [HoTen], [CK], [NamSinh], [F6], [TinhThanh], [LoaiHD], [GioiTinh], [F14], [DiaChi], [F16], [Phone]) VALUES (6, N'06', N'TRẦN TRUNG HÀO ', N'Bác sĩ chuyên khoa nội', CAST(N'1960-07-07T00:00:00.000' AS DateTime), N'201854280', N'Đà Nẵng', N'Không xác định thời hạn', N'Nam ', N'Đà Nẵng ', N'Tổ 5, phường Hòa Phát, quận Cẩm Lệ, TP Đà Nẵng', N'Tổ 5, phường Hòa Phát, quận Cẩm Lệ, TP Đà Nẵng', N'098 428 8041')
GO
INSERT [dbo].[DM_NV] ([F1], [F2], [HoTen], [CK], [NamSinh], [F6], [TinhThanh], [LoaiHD], [GioiTinh], [F14], [DiaChi], [F16], [Phone]) VALUES (7, N'07', N'TRẦN VĂN CẢNH ', N'Bác sĩ chuyên khoa mắt', NULL, N'183160825', N'Hà Tĩnh', N'Không xác định thời hạn', N'Nam ', N'Hà Tĩnh ', N'Tổ 36, phường Hòa Thọ Đông, quận Cẩm Lệ, Thành phố Đà Nẵng ', N'Tổ 36, phường Hòa Thọ Đông, quận Cẩm Lệ, Thành phố Đà Nẵng ', N'090 590 1569')
GO
INSERT [dbo].[DM_NV] ([F1], [F2], [HoTen], [CK], [NamSinh], [F6], [TinhThanh], [LoaiHD], [GioiTinh], [F14], [DiaChi], [F16], [Phone]) VALUES (8, N'08', N'DƯƠNG THỊ THU THẢO', N'Trung cấp kế toán', NULL, N'201798614', N'Đà Nẵng', N'Không xác định thời hạn', N'Nữ ', N'Quảng Nam ', N'Tổ 47 P hường Hòa Khánh Nam, Quận Liên Chiểu, TP Đà Nẵng', N'H74/04/53 Hoàng Văn Thái, Phường Hòa Khánh Nam, TP Đà Nẵng', N'093 492 9877')
GO
INSERT [dbo].[DM_NV] ([F1], [F2], [HoTen], [CK], [NamSinh], [F6], [TinhThanh], [LoaiHD], [GioiTinh], [F14], [DiaChi], [F16], [Phone]) VALUES (9, N'09', N'LÊ VĂN DẦN ', N'Cử nhân X quang', CAST(N'1964-01-01T00:00:00.000' AS DateTime), N'201755164', N'Đà Nẵng', N'Không xác định thời hạn', N'Nam ', N'Quảng Ngãi ', N'Tổ 59, Phường Hòa Thuận Đông, Quận Cẩm Lệ, Thành phố Đà Nẵng ', N'Tổ 59, Phường Hòa Thuận Đông, Quận Cẩm Lệ, Thành phố Đà Nẵng ', N'097 202 2216')
GO
INSERT [dbo].[DM_NV] ([F1], [F2], [HoTen], [CK], [NamSinh], [F6], [TinhThanh], [LoaiHD], [GioiTinh], [F14], [DiaChi], [F16], [Phone]) VALUES (10, N'10', N'NGUYỄN THỊ HOÀI TÚ', N'KTV Xét nghiệm ', NULL, N'205394244', N'Quảng Nam', N'Không xác định thời hạn', N'Nữ', N'Quảng Nam ', N'Khu Sinh Thái Hòa Xuân, Phường Hòa Xuân, Quận Cẩm Lệ, Tp Đà Nẵng', N'Khu Sinh Thái Hòa Xuân, Phường Hòa Xuân, Quận Cẩm Lệ, Tp Đà Nẵng', N' 090 588 1206')
GO
INSERT [dbo].[DM_NV] ([F1], [F2], [HoTen], [CK], [NamSinh], [F6], [TinhThanh], [LoaiHD], [GioiTinh], [F14], [DiaChi], [F16], [Phone]) VALUES (11, N'11', N'TRƯƠNG PHÚ TRINH ', N'Dược sĩ đại học', CAST(N'1967-09-08T00:00:00.000' AS DateTime), N'200791944', N'Quảng Nam', N'Không xác định thời hạn', N'Nam ', N'Quảng Nam ', N'Tổ 27 P. Tam Thuận, Quận Thanh Khê, Tp Đà Nẵng ', N'Tổ 27 P. Tam Thuận, Quận Thanh Khê, Tp Đà Nẵng ', N'091 348 8017')
GO
INSERT [dbo].[DM_NV] ([F1], [F2], [HoTen], [CK], [NamSinh], [F6], [TinhThanh], [LoaiHD], [GioiTinh], [F14], [DiaChi], [F16], [Phone]) VALUES (12, N'12', N'NGUYỄN HỮU VĨNH ', N'Bác sĩ chuyên khoa CĐHA', NULL, N'205482993', N'Quảng Nam', N'Không xác định thời hạn', N'Nam', N'Quảng Nam ', N'Số 79 An Hải 6, Tổ 117, An Hải Bắc, Quận Sơn Trà, Tp Đà Nẵng', N'Số 79 An Hải 6, Tổ 117, An Hải Bắc, Quận Sơn Trà, Tp Đà Nẵng', N'091 766 6611')
GO
INSERT [dbo].[DM_NV] ([F1], [F2], [HoTen], [CK], [NamSinh], [F6], [TinhThanh], [LoaiHD], [GioiTinh], [F14], [DiaChi], [F16], [Phone]) VALUES (13, N'13', N'NGUYỄN THỊ THU PHƯƠNG ', N'Bác sĩ chuyên khoa da liễu', CAST(N'1992-10-10T00:00:00.000' AS DateTime), N'183993613', N'Hà Tĩnh', N'Không xác định thời hạn', N'Nữ', N'Hà Tĩnh ', N'Thôn Phú Thượng, Xã Kỳ Khang, Huyện Kỳ Anh, Hà Tĩnh', N'150 Nguyễn Chánh, Phường Hòa Khánh Bắc, Quận Liên Chiểu, Tp Đà Nẵng', N'039 264 6960')
GO
INSERT [dbo].[DM_NV] ([F1], [F2], [HoTen], [CK], [NamSinh], [F6], [TinhThanh], [LoaiHD], [GioiTinh], [F14], [DiaChi], [F16], [Phone]) VALUES (14, N'14', N'NGUYỄN THỊ NGỌC LINH', N'KTV VLTL-PHCN', NULL, N'201713430', N'Đà Nẵng', N'01 năm', N'Nữ', N'Đà Nẵng', N'Tổ 64, phường Hòa Khánh Nam, quận Liên Chiểu, TP Đà Nẵng', N'Tổ 64, phường Hòa Khánh Nam, quận Liên Chiểu, TP Đà Nẵng', N'070 2474 339')
GO
INSERT [dbo].[DM_NV] ([F1], [F2], [HoTen], [CK], [NamSinh], [F6], [TinhThanh], [LoaiHD], [GioiTinh], [F14], [DiaChi], [F16], [Phone]) VALUES (15, N'15', N'NGUYỄN TIẾN CHUNG ', N'Bác sĩ chuyên khoa SPK', NULL, N'201486936', N'Đà Nẵng ', N'Không xác định thời hạn', N'Nam ', N'Đà Nẵng ', N'Thôn Phú Hạ, Xã Hòa Sơn, Huyện Hòa Vang, thành phố Đà Nẵng ', N'Thôn Phú Hạ, Xã Hòa Sơn, Huyện Hòa Vang, thành phố Đà Nẵng ', N'093 514 4604')
GO
INSERT [dbo].[DM_NV] ([F1], [F2], [HoTen], [CK], [NamSinh], [F6], [TinhThanh], [LoaiHD], [GioiTinh], [F14], [DiaChi], [F16], [Phone]) VALUES (16, N'16', N'HUỲNH THỊ BÍCH HẠNH ', N'Bác sĩ chuyên khoa SPK', NULL, N'205114026', N'Quảng Nam', N'Không xác định thời hạn', N'Nữ', N'Quảng Nam ', N'Tam Xuân 1, Núi Thành, Quảng Nam ', N'Tam Xuân 1, Núi Thành, Quảng Nam ', N'090 1270 484')
GO
INSERT [dbo].[DM_NV] ([F1], [F2], [HoTen], [CK], [NamSinh], [F6], [TinhThanh], [LoaiHD], [GioiTinh], [F14], [DiaChi], [F16], [Phone]) VALUES (17, N'17', N'ĐOÀN NHẬT KHÁNH ', N'Bác sĩ chuyên khoa TMH', NULL, N'191624546', N'Thừa Thiên Huế', N'Không xác định thời hạn', N'Nam ', N'Huế', N'Lộc Bổn, Phú Lộc, Thừa Thiên Huế', N'34/48 Âu Cơ, Phường Hòa Khánh Bắc, Quận Liên Chiểu, TP Đà Nẵng ', N'098 881 3450')
GO
INSERT [dbo].[DM_NV] ([F1], [F2], [HoTen], [CK], [NamSinh], [F6], [TinhThanh], [LoaiHD], [GioiTinh], [F14], [DiaChi], [F16], [Phone]) VALUES (18, N'18', N'LƯƠNG QUANG TỨ ', N'Bác sĩ chuyên khoa RHM', NULL, N'891045078', N'Quân Khu 5', N'Không xác định thời hạn', N'Nam ', N'Quảng Nam ', N'330/01 Phường  Hòa Thuận Tây, quận Hải Châu, TP Đà Nẵng ', N'330/01 Phường  Hòa Thuận Tây, quận Hải Châu, TP Đà Nẵng ', N'090 5187 736')
GO
INSERT [dbo].[DM_NV] ([F1], [F2], [HoTen], [CK], [NamSinh], [F6], [TinhThanh], [LoaiHD], [GioiTinh], [F14], [DiaChi], [F16], [Phone]) VALUES (19, N'19', N'TRẦN VŨ ANH ', N'Bác sĩ chuyên khoa CĐHA', CAST(N'1969-12-01T00:00:00.000' AS DateTime), N'201513525', N'Đà Nẵng ', N'Không xác định thời hạn', N'Nam ', N'Hà Tĩnh', N'Tổ 80 Phường An Hải Bắc, quận Sơn Trà, Thành phố Đà Nẵng ', N'Tổ 80 Phường An Hải Bắc, quận Sơn Trà, Thành phố Đà Nẵng ', N'098 364 5419')
GO
INSERT [dbo].[DM_NV] ([F1], [F2], [HoTen], [CK], [NamSinh], [F6], [TinhThanh], [LoaiHD], [GioiTinh], [F14], [DiaChi], [F16], [Phone]) VALUES (20, N'20', N'NGUYỄN HOÀNH SINH ', N'Bác sĩ chuyên khoa ngoại', NULL, N'201614972', N'Đà Nẵng ', N'Không xác định thời hạn', N'Nam ', N'Thanh Hóa', N'Tổ 55 Phường Hòa Cường Bắc, Quận Hải Châu, Thành phố Đà Nẵng', N'Tổ 55 Phường Hòa Cường Bắc, Quận Hải Châu, Thành phố Đà Nẵng', N'091 405 5255')
GO
INSERT [dbo].[DM_NV] ([F1], [F2], [HoTen], [CK], [NamSinh], [F6], [TinhThanh], [LoaiHD], [GioiTinh], [F14], [DiaChi], [F16], [Phone]) VALUES (21, N'21', N'NGUYỄN THỊ VÂN ANH', N'Điều dưỡng cao đẳng', NULL, N'194425947', N'Quảng Bình', N'01 năm', N'Nữ', N'Quảng Bình', N'Thôn Xuân Hạ, xã Văn Hóa, Huyện Tuyên Hóa, tỉnh Quảng Bình', N'229, Âu Cơ, phường Hòa Khánh Bắc, quận Liên Chiểu, thành phố Đà Nẵng', N'079 345 7752')
GO
INSERT [dbo].[DM_NV] ([F1], [F2], [HoTen], [CK], [NamSinh], [F6], [TinhThanh], [LoaiHD], [GioiTinh], [F14], [DiaChi], [F16], [Phone]) VALUES (22, N'22', N'NGUYỄN THỊ NGÀN', N'KTV Chẩn đoán hình ảnh', NULL, N'197322772', N'Quảng Trị', N'Không xác định thời hạn', N'Nữ', N'Quảng Trị ', N'Vĩnh Hiền, Vĩnh Linh, Quảng Trị ', N'206 Phan Trọng Tuệ, quận Hải Châu, Thành phố Đà Nẵng', N'039 717 9806')
GO
INSERT [dbo].[DM_NV] ([F1], [F2], [HoTen], [CK], [NamSinh], [F6], [TinhThanh], [LoaiHD], [GioiTinh], [F14], [DiaChi], [F16], [Phone]) VALUES (23, N'23', N'PHẠM ĐÌNH HUY', N'Dược sĩ ', NULL, N'201687429', N'Đà Nẵng ', N'01 năm', N'Nam', N'Đà Nẵng', N'K72/37 Phan Văn Định, phường Hòa Khánh Bắc, quận Liên Chiểu, TP Đà Nẵng', N'K72/37 Phan Văn Định, phường Hòa Khánh Bắc, quận Liên Chiểu, TP Đà Nẵng', N'076 654 7308')
GO
INSERT [dbo].[DM_NV] ([F1], [F2], [HoTen], [CK], [NamSinh], [F6], [TinhThanh], [LoaiHD], [GioiTinh], [F14], [DiaChi], [F16], [Phone]) VALUES (24, N'24', N'NGUYỄN THỊ THANH HOA ', N'Hộ sinh viên cao đẳng', NULL, N'184205769', N'Hà Tĩnh ', N'01 năm', N'Nữ', N'Hà Tĩnh ', N'Đức Đồng, Đức Thọ, Hà Tĩnh ', N'Tổ 14, Phường Thọ Quang, Quận Sơn Trà, Thành phố Đà Nẵng', N'098 173 4746')
GO
INSERT [dbo].[DM_NV] ([F1], [F2], [HoTen], [CK], [NamSinh], [F6], [TinhThanh], [LoaiHD], [GioiTinh], [F14], [DiaChi], [F16], [Phone]) VALUES (25, N'25', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[DM_NV] ([F1], [F2], [HoTen], [CK], [NamSinh], [F6], [TinhThanh], [LoaiHD], [GioiTinh], [F14], [DiaChi], [F16], [Phone]) VALUES (26, N'26', N'ĐOÀN THỊ NGỌC LỆ', N'Y sĩ YHCT', NULL, N'205596367', N'Quảng Nam', N'01 năm', N'Nữ', N'Quảng Nam ', N'Xã Đại Chánh, Đại Lộc, Quảng Nam ', N'303 Phạm Như Xương, Quận Liên Chiểu, TP Đà Nẵng', N'093 574 3702')
GO
INSERT [dbo].[DM_NV] ([F1], [F2], [HoTen], [CK], [NamSinh], [F6], [TinhThanh], [LoaiHD], [GioiTinh], [F14], [DiaChi], [F16], [Phone]) VALUES (27, N'27', N'TRƯƠNG THU THỦY', N'Bác sỹ Sản phụ khoa', NULL, N'201451965', N'Đà Nẵng', N'Không xác định thời hạn', NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[DM_NV] ([F1], [F2], [HoTen], [CK], [NamSinh], [F6], [TinhThanh], [LoaiHD], [GioiTinh], [F14], [DiaChi], [F16], [Phone]) VALUES (28, N'28', N'HỒ THỊ HỒNG NGA', N'Cử nhân điều dưỡng', NULL, N'201687045', N'Đà Nẵng', N'01 năm', N'Nữ', N'Đà Nẵng', N'176 Đồng Kè, phường Hòa Khánh Bắc, quân Liên Chiểu, TP Đà Nẵng', N'176 Đồng Kè, phường Hòa Khánh Bắc, quân Liên Chiểu, TP Đà Nẵng', N'077 332 0920')
GO
INSERT [dbo].[DM_NV] ([F1], [F2], [HoTen], [CK], [NamSinh], [F6], [TinhThanh], [LoaiHD], [GioiTinh], [F14], [DiaChi], [F16], [Phone]) VALUES (29, N'29', N'HUỲNH THỊ THANH THÚY', N'Dược sĩ trung học', NULL, N'201467145', N'Đà Nẵng', N'03 tháng', N'Nữ', N'Quảng Nam ', N'Tổ 12 Hòa Cường Bắc, Quận Hải Châu, Tp Đà Nẵng ', N'K134-H29/1 Lê Hữu Trác, Phường An Hải Đông, Quận Sơn Trà, TP Đà nẵng', N'090 582 6827')
GO
INSERT [dbo].[DM_NV] ([F1], [F2], [HoTen], [CK], [NamSinh], [F6], [TinhThanh], [LoaiHD], [GioiTinh], [F14], [DiaChi], [F16], [Phone]) VALUES (30, N'30', N'HỒ THẢO NGUYÊN', N'Điều dưỡng cao đẳng', NULL, N'201633528', N'Đà Nẵng ', N'Không xác định thời hạn', N'Nữ', N'Đà Nẵng ', N'Tổ 26 Phường Hòa Khánh Bắc, Quận Liên Chiểu, thành phố Đà Nẵng ', N'K634/47 Trưng Nữ Vương, Hòa Thuận Tây, Quận Hải Châu, TP Đà Nẵng ', N'090 524 5842')
GO
INSERT [dbo].[DM_NV] ([F1], [F2], [HoTen], [CK], [NamSinh], [F6], [TinhThanh], [LoaiHD], [GioiTinh], [F14], [DiaChi], [F16], [Phone]) VALUES (31, N'31', N'TRẦN THỊ THÁI TÂM', N'Hộ lý', NULL, N'201455430', N'Đà Nẵng', N'01 năm', N'Nữ', N'Đà Nẵng', N'Điện Phước, Điện Bàn, Quảng Nam', N'K138, Hoàng Văn Thái, phường Hòa Khánh Nam, Quận Liên Chiểu, TP Đà Nẵng', N'076 255 1155')
GO
INSERT [dbo].[DM_NV] ([F1], [F2], [HoTen], [CK], [NamSinh], [F6], [TinhThanh], [LoaiHD], [GioiTinh], [F14], [DiaChi], [F16], [Phone]) VALUES (32, N'32', N'PHAN THỊ NHUNG', N'Hộ lý', NULL, N'201584405', N'Đà Nẵng', N'01 năm', N'Nữ', N'Đà Nẵng ', N'Tổ 42, Phường Hòa Hiệp Bắc, Quận Liên Chiểu, Tp Đà nẵng ', N'Tổ 7 Kim Liên, Phường Hòa Hiệp Bắc, Quận Liên Chiểu, Tp Đà Nẵng', N'090 5024 250')
GO
INSERT [dbo].[DM_NV] ([F1], [F2], [HoTen], [CK], [NamSinh], [F6], [TinhThanh], [LoaiHD], [GioiTinh], [F14], [DiaChi], [F16], [Phone]) VALUES (33, N'33', N'NGUYỄN TIẾN DŨNG', N'Bảo vệ kiêm điện nước', NULL, N'201352314', N'Đà Nẵng', N'Không xác định thời hạn', N'Nam ', N'Quảng Nam', N'Tổ 52, phường Hòa Cường Bắc, Quận Hải Châu, TP Đà Nẵng', N'Tổ 52, phường Hòa Cường Bắc, Quận Hải Châu, TP Đà Nẵng', N'098 5009 964')
GO
INSERT [dbo].[DM_NV] ([F1], [F2], [HoTen], [CK], [NamSinh], [F6], [TinhThanh], [LoaiHD], [GioiTinh], [F14], [DiaChi], [F16], [Phone]) VALUES (34, N'34', N'HUỲNH VĂN VĨ', N'Dược sĩ cao đẳng', NULL, N'201725238', N'Đà Nẵng', N'01 năm', N'Nam', N'Đà Nẵng', N'Xã Hòa Liên, huyện Hòa Vang, thành phố Đà Nẵng', N'Xã Hòa Liên, huyện Hòa Vang, thành phố Đà Nẵng', N' 078 3805 690')
GO
INSERT [dbo].[DM_NV] ([F1], [F2], [HoTen], [CK], [NamSinh], [F6], [TinhThanh], [LoaiHD], [GioiTinh], [F14], [DiaChi], [F16], [Phone]) VALUES (35, N'35', N'LÊ THỊ MINH', N'Điều dưỡng cao đẳng', NULL, N'187107854', N'Nghệ An', N'01 năm', N'Nữ', N'Nghệ An', N'Đội 1, xã Đông Thanh, huyện Đông Sơn, tỉnh Thanh Hóa', N'Số 16, Phan Văn Định, quận Liên Chiểu, thành phố Đà Nẵng', N'035 937 8516')
GO
INSERT [dbo].[DM_NV] ([F1], [F2], [HoTen], [CK], [NamSinh], [F6], [TinhThanh], [LoaiHD], [GioiTinh], [F14], [DiaChi], [F16], [Phone]) VALUES (36, N'36', N'DƯƠNG VĂN LÂM ', N'Bác sĩ chuyên khoa CĐHA', NULL, N'861044453', N'Quân Khu 5', N'Không xác định thời hạn', N'Nam ', N'Đà Nẵng ', N'Mỹ An, quận Ngũ Hành Sơn, Thành phố Đà Nẵng', N'Mỹ An, quận Ngũ Hành Sơn, Thành phố Đà Nẵng', N'098 311 4663')
GO
INSERT [dbo].[DM_NV] ([F1], [F2], [HoTen], [CK], [NamSinh], [F6], [TinhThanh], [LoaiHD], [GioiTinh], [F14], [DiaChi], [F16], [Phone]) VALUES (37, N'37', N'DƯƠNG THỊ HƯƠNG', N'Điều dưỡng cao đẳng', NULL, N'197287248', N'Quảng Trị', N'01 năm', N'Nữ', N'Quảng Trị', N'Hải Lâm, Hải Lăng, Quảng Trị', N'Hải Lâm, Hải Lăng, Quảng Trị', N'035 363 5353')
GO
INSERT [dbo].[DM_NV] ([F1], [F2], [HoTen], [CK], [NamSinh], [F6], [TinhThanh], [LoaiHD], [GioiTinh], [F14], [DiaChi], [F16], [Phone]) VALUES (38, N'38', N'PHẠM THỊ DUNG', N'Kế toán đại học', NULL, N'201764932', N'Đà Nẵng', N'Không xác định thời hạn', N'Nữ', N'Thanh Hóa', N'Tổ 36B, Quang Thành 4A, phường Hòa Khánh Bắc, quận Liên Chiểu, T Đà Nẵng', N'Tổ 36B, Quang Thành 4A, phường Hòa Khánh Bắc, quận Liên Chiểu, T Đà Nẵng', N'093 3876 288')
GO
INSERT [dbo].[DM_NV] ([F1], [F2], [HoTen], [CK], [NamSinh], [F6], [TinhThanh], [LoaiHD], [GioiTinh], [F14], [DiaChi], [F16], [Phone]) VALUES (39, N'39', N'TRẦN ĐÌNH CƯỜNG ', N'Bác sĩ nội soi tiêu hóa', NULL, N'206380328', N'Quảng Nam', N'Không xác định thời hạn', N'Nam', N'Quảng Nam ', N'Tổ 94, Phường Hòa Cường Nam, Quận Hải Châu, TP Đà Nẵng ', N'Tổ 94, Phường Hòa Cường Nam, Quận Hải Châu, TP Đà Nẵng ', N'098 226 4203')
GO
INSERT [dbo].[DM_NV] ([F1], [F2], [HoTen], [CK], [NamSinh], [F6], [TinhThanh], [LoaiHD], [GioiTinh], [F14], [DiaChi], [F16], [Phone]) VALUES (40, N'40', N'MAI TẤN MẪN ', N'Bác sĩ chuyên khoa nội', NULL, N'200903835', N'Đà Nẵng ', N'Không xác định thời hạn', N'Nam', N'Quảng Nam ', N'Tổ 38, P An Hải Bắc, Q Sơn Trà, TP Đà Nẵng ', N'Tổ 38, P An Hải Bắc, Q Sơn Trà, TP Đà Nẵng ', N'091 342 0665')
GO
INSERT [dbo].[DM_NV] ([F1], [F2], [HoTen], [CK], [NamSinh], [F6], [TinhThanh], [LoaiHD], [GioiTinh], [F14], [DiaChi], [F16], [Phone]) VALUES (41, N'41', N'PHẠM TẤN TRINH ', N'Kỹ thuật viên xét nghiệm', NULL, N'212823830', N'Quảng Ngãi', N'01 năm', N'Nam', N'Quảng Ngãi', N'Xã Bình Châu, huyện BÌnh Sơn, tỉnh Quảng Ngãi', N'257 Tôn Đản, phường Hòa An, quận Cẩm Lệ, TP Đà Nẵng', N'039 6361 377')
GO
INSERT [dbo].[DM_NV] ([F1], [F2], [HoTen], [CK], [NamSinh], [F6], [TinhThanh], [LoaiHD], [GioiTinh], [F14], [DiaChi], [F16], [Phone]) VALUES (42, N'42', N'VÕ ANH VỸ', N'Kỹ thuật viên xét nghiệm', NULL, N'205718019', N'Đà Nẵng', N'01 năm', N'Nam', N'Quảng Nam', N'Thôn 4, xã Bình Giang, huyện Thăng Bình, tỉnh Quảng Nam', N'76H1/5 Lê Vĩnh Huy, Phường Hòa Cường Bắc, Quận Hải Châu , thành phố Đà Nẵng', N'035 4980 647')
GO
INSERT [dbo].[DM_NV] ([F1], [F2], [HoTen], [CK], [NamSinh], [F6], [TinhThanh], [LoaiHD], [GioiTinh], [F14], [DiaChi], [F16], [Phone]) VALUES (43, N'43', N'NGUYỄN ÁNH SƯƠNG', N'Bác sĩ chuyên khoa VLTL-PHCN', NULL, N'201464385', N'Đà Nẵng', N'Không xác định thời hạn', N'Nam', N'Đà Nẵng', N'Tổ 6, Bình Thuận, quận Hải Châu, thành phố Đà Nẵng', N'Tổ 6, Bình Thuận, quận Hải Châu, thành phố Đà Nẵng', N'090 6091 489')
GO
INSERT [dbo].[DM_NV] ([F1], [F2], [HoTen], [CK], [NamSinh], [F6], [TinhThanh], [LoaiHD], [GioiTinh], [F14], [DiaChi], [F16], [Phone]) VALUES (44, N'44', N'PHẠM THỊ HOÀI HƯƠNG', N'Điều dưỡng trung cấp', NULL, N'201583483', N'Đà Nẵng', N'01 năm', N'Nữ', N'Đà Nẵng', N'Thôn Phú Hạ, xã Hòa Sơn, huyện Hòa Vang, TP Đà Nẵng', N'Thôn Phú Hạ, xã Hòa Sơn, huyện Hòa Vang, TP Đà Nẵng', N'077 458 2682')
GO
INSERT [dbo].[DM_NV] ([F1], [F2], [HoTen], [CK], [NamSinh], [F6], [TinhThanh], [LoaiHD], [GioiTinh], [F14], [DiaChi], [F16], [Phone]) VALUES (45, N'45', N'TRƯƠNG THỊ THÙY THẢO', N'Bác sỹ chuyên khoa nhi', NULL, N'205266280', N'Quảng Nam', N'Không xác định thời hạn', N'Nữ', N'Quảng Nam', N'Tổ 10, phường Tân Chính, quận Thanh Khê, thành phố Đà Nẵng', N'Tổ 10, phường Tân Chính, quận Thanh Khê, thành phố Đà Nẵng', N'097 537 6887')
GO
